// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using recipeList.Data;

#nullable disable

namespace recipeList.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230506124640_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("recipeList.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Recipeid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Recipeid");

                    b.ToTable("products");
                });

            modelBuilder.Entity("recipeList.Models.Recipe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Userid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Userid");

                    b.ToTable("recipes");
                });

            modelBuilder.Entity("recipeList.Models.User", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("recipeList.Models.Product", b =>
                {
                    b.HasOne("recipeList.Models.Recipe", null)
                        .WithMany("products")
                        .HasForeignKey("Recipeid");
                });

            modelBuilder.Entity("recipeList.Models.Recipe", b =>
                {
                    b.HasOne("recipeList.Models.User", null)
                        .WithMany("recipes")
                        .HasForeignKey("Userid");
                });

            modelBuilder.Entity("recipeList.Models.Recipe", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("recipeList.Models.User", b =>
                {
                    b.Navigation("recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
